### ISSUE TITLE
Slideshow in Flexibility 5

### ISSUE THREAD

**Issue by Jhcbiinoc2** [DESIGNfromWITHIN/flexibility5#2]
I have tried everything and I still cannot locate anywhere to configure the image slider...can someone please help me with this?  I really want to use this theme, but I am beyond frustrated...thank you for any help you can provide.

**Comment by DESIGNfromWITHIN** [comment]
@Jhcbiinoc2 It is on the Homepage under 'Template variables' > 'Slider'
